CREATE DATABASE BDFUTBOL
GO

USE BDFUTBOL
GO

CREATE TABLE CONTINENTE(
IDE_CON INT IDENTITY(1,1) PRIMARY KEY,
NOM_CON VARCHAR(35) NOT NULL
)
GO

INSERT INTO CONTINENTE (NOM_CON) VALUES ('ASIA')
INSERT INTO CONTINENTE (NOM_CON) VALUES ('AFRICA')
INSERT INTO CONTINENTE (NOM_CON) VALUES ('AMERICA')
INSERT INTO CONTINENTE (NOM_CON) VALUES ('EUROPA')
GO 

CREATE TABLE PAIS (
IDE_PAIS INT IDENTITY(1,1) PRIMARY KEY,
NOM_PAIS VARCHAR(35) NOT NULL,
IDE_CON_PAIS INT NOT NULL
CONSTRAINT fk_CON_PAIS FOREIGN KEY (IDE_CON_PAIS) REFERENCES CONTINENTE 
)
GO

INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('COREA DEL SUR',1)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('CHINA',1)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('CAMERUN',2)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('COSTA DE MARFIL',2)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('EGIPTO',2)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('SENEGAL',2)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('ARGENTINA',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('BRASIL',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('CHILE',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('COLOMBIA',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('PERU',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('URUGUAY',3)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('ALEMANIA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('BELGICA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('CROACIA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('ESPAÑA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('FRANCIA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('ITALIA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('HOLANDA',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('PORTUGAL',4)
INSERT INTO PAIS (NOM_PAIS,IDE_CON_PAIS) VALUES ('INGLATERRA',4)



CREATE TABLE JUGADOR(
IDE_JUG	INT	NOT NULL PRIMARY KEY IDENTITY(1,1),
NOM_JUG	VARCHAR(35) NOT NULL,
FNA_JUG	DATE NOT NULL,
IDE_PAIS INT REFERENCES PAIS,
IDE_CON INT REFERENCES CONTINENTE,
PES_JUG	DECIMAL(5,2) NOT NULL
)
GO

INSERT INTO JUGADOR(NOM_JUG,FNA_JUG,IDE_PAIS,IDE_CON,PES_JUG) VALUES ('LIONEL MESSI','1987/06/24',7,3,'72.00')