USE BDFUTBOL
GO

CREATE PROCEDURE SP_LISTAR_CONTINENTE
AS
BEGIN
	SELECT * FROM CONTINENTE
END
GO

CREATE PROCEDURE SP_LISTAR_PAIS
(@IDE_CON_PAIS INT)
AS
BEGIN
	SELECT * FROM PAIS WHERE IDE_CON_PAIS=@IDE_CON_PAIS
END
GO

CREATE PROCEDURE SP_LISTAR_JUGADOR
AS
BEGIN
	SELECT J.IDE_JUG,J.NOM_JUG,J.FNA_JUG,P.IDE_PAIS,P.NOM_PAIS,C.IDE_CON,C.NOM_CON,J.PES_JUG FROM JUGADOR J INNER JOIN PAIS P ON J.IDE_PAIS = P.IDE_PAIS INNER JOIN CONTINENTE C ON C.IDE_CON = J.IDE_CON
END
GO

CREATE PROCEDURE SP_INSERTAR_JUGADOR
(@NOM_JUG VARCHAR(35),@FNA_JUG DATE,@IDE_PAIS INT,@IDE_CON INT,@PES_JUG DECIMAL(5,2))
AS
BEGIN
	INSERT INTO JUGADOR(NOM_JUG,FNA_JUG,IDE_PAIS,IDE_CON,PES_JUG) VALUES (@NOM_JUG,@FNA_JUG,@IDE_PAIS,@IDE_CON,@PES_JUG)
END
GO
	
EXEC SP_INSERTAR_JUGADOR 'CRISTIANO RONALDO','1985/02/05',20,4,'84.00'
EXEC SP_INSERTAR_JUGADOR 'PAOLO GUERRERO','1984/01/01',11,3,'82.00'
GO


CREATE PROCEDURE SP_ACTUALIZAR_JUGADOR
(@IDE_JUG INT,@NOM_JUG VARCHAR(35),@FNA_JUG DATE,@IDE_PAIS INT,@IDE_CON INT,@PES_JUG DECIMAL(5,2))
AS
BEGIN
	UPDATE JUGADOR
	SET NOM_JUG=@NOM_JUG,FNA_JUG=@FNA_JUG, IDE_PAIS=@IDE_PAIS,IDE_CON=@IDE_CON, PES_JUG=@PES_JUG
	WHERE IDE_JUG=@IDE_JUG
END
GO

CREATE PROCEDURE SP_ELIMINAR_JUGADOR
(@IDE_JUG INT)
AS
BEGIN
	DELETE FROM JUGADOR WHERE IDE_JUG=@IDE_JUG
END
GO
